tag-pattern: &tag-pattern
  only: /^\d+\.\d+\.\d+$/

version: 2.1

executors:
  node:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest

jobs:
  setup:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: lock-{{ checksum "yarn.lock" }}
      - run:
          command: yarn
      - save_cache:
          key: lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          command: yarn lint

  tests:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          command: yarn test

  commitlint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          command: ~/project/scripts/commitilint_range.sh
          
  publish:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: yarn publish

workflows:
  version: 2
  ci:
    jobs:
      - setup

      - lint:
          requires:
            - setup

      - tests:
          requires:
            - setup

      - commitlint:
          requires:
            - setup
      
  release:
    jobs:
      - setup:
          filters:
            branches:
              ignore: /.*/
            tags:
              <<: *tag-pattern

      - publish:
          context: org-global
          requires:
            - setup
          filters:
            branches:
              ignore: /.*/
            tags:
              <<: *tag-pattern
