name: ci

on: [push, pull_request]

jobs:
  main:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: install dependencies
        run: yarn

      - name: lint
        run: yarn lint
        env:
          CI: true

      - uses: wagoid/commitlint-github-action@v4

      - name: unit tests
        run: yarn test
        env:
          CI: true
